version: '3.4'

services:
  sql-db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_USER: root
      POSTGRES_DB: test_db
    ports:
      - '5050:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  redis-cache:
    image: redis:5.0.5-alpine
    restart: always
    ports:
      - '5051:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  postgres-data:
