services:
  back:
    build:
      context: .
      dockerfile: Dockerfile.dev.back
    ports:
      - 3435:3435
    volumes:
      - ./:/code
  postgresql:
    env_file:
      - .env
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: root
      POSTGRES_DB: nick_dot_ng
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data/
  redis:
    image: redis:alpine
    volumes:
      - ./volumes/redis:/data
